library(tidyverse)
data <- read.csv("data/main_data.csv")
data_ORR <- data %>% 
  select(ID, Inclusion_Exlusion, ORR_Registry, ORR_Protocol, ORR_Prespecified, ORR_Paper, 
         ORR_Inconsistency, ORR_Reason, ORR_Blndeness) %>% 
  filter(Inclusion_Exlusion=="Inclusion") %>% 
  rename(Registry=ORR_Registry, Protocol=ORR_Protocol, Prespecified=ORR_Prespecified, 
         Published_paper=ORR_Paper, Inconsistency=ORR_Inconsistency, 
         Reason=ORR_Reason, Blindness=ORR_Blndeness) %>% 
  mutate(Registry=case_when(Registry=="Investigator + central"~"Central + local",
                            Registry=="Only central"~"Only central",
                            Registry=="Only investigator"~"Only local",
                            Registry=="Unclear"~"Unclear",
                            Registry=="No ORR"~"No ORR",
                            Registry=="No registry"~"Not available"),
         Protocol=case_when(Protocol=="Investigator + central"~"Central + local",
                            Protocol=="Only central"~"Only central",
                            Protocol=="Only investigator"~"Only local",
                            Protocol=="Unclear"~"Unclear",
                            Protocol=="No ORR"~"No ORR",
                            Protocol=="No protocol"~"Not available"),
         Prespecified=case_when(Prespecified=="Investigator + central"~"Central + local",
                                Prespecified=="Only central"~"Only central",
                                Prespecified=="Only investigator"~"Only local",
                                Prespecified=="Unclear"~"Unclear",
                                Prespecified=="No ORR"~"No ORR",
                                Prespecified=="Not available"~"Not available"),
         Published_paper=case_when(Published_paper=="Investigator + central"~"Central + local",
                                   Published_paper=="Only central"~"Only central",
                                   Published_paper=="Only investigator"~"Only local",
                                   Published_paper=="Unclear"~"Unclear",
                                   Published_paper=="No ORR"~"No ORR"),
         Blindness2=case_when(Blindness=="Non-blinded + blinded"~"Reported",
                              Blindness=="Only blinded"~"Reported",
                              Blindness=="Only non-blinded"~"Reported",
                              Blindness=="Probably, non-blinded + blinded"~"Not reported",
                              Blindness=="Probably, only blinded"~"Not reported",
                              Blindness=="Probably, only non-blinded"~"Not reported",
                              Blindness=="No ORR"~"No ORR"),
         Blindness=case_when(Blindness=="Non-blinded + blinded"~"Blinded + non-blinded",
                             Blindness=="Only blinded"~"Only blinded",
                             Blindness=="Only non-blinded"~"Only non-blinded",
                             Blindness=="Probably, non-blinded + blinded"~"Probably, blinded + non-blinded",
                             Blindness=="Probably, only blinded"~"Probably, only blinded",
                             Blindness=="Probably, only non-blinded"~"Probably, only non-blinded",
                             Blindness=="No ORR"~"No ORR"),
         Inconsistency=case_when(Inconsistency=="Consistent"~"Consistent",
                                 Inconsistency=="Consistent: unclear"~"Unclear both in prespecification and in paper",
                                 Inconsistency=="Not prespecified"~"No prespecification, or no mention",
                                 Inconsistency=="Unclear in advance but clear in paper"~"Unclear in advance but clear in paper",
                                 Inconsistency=="Central or local in advance but both in paper"~"Central or local in advance but both in paper",
                                 Inconsistency=="Central or local in advance but unclear in paper"~"Central or local in advance but unclear in paper",
                                 Inconsistency=="Suspicious of selective reporting"~"Suspicious of selective reporting")) %>% 
  transform(Registry= factor(Registry, levels = c("Central + local", 
                                                  "Only central", 
                                                  "Only local", 
                                                  "Unclear", 
                                                  "No ORR", 
                                                  "Not available")),
            Protocol= factor(Protocol, levels = c("Central + local", 
                                                  "Only central", 
                                                  "Only local", 
                                                  "Unclear", 
                                                  "No ORR", 
                                                  "Not available")),
            Prespecified= factor(Prespecified, levels = c("Central + local", 
                                                          "Only central", 
                                                          "Only local", 
                                                          "Unclear", 
                                                          "No ORR", 
                                                          "Not available")),
            Published_paper= factor(Published_paper, levels = c("Central + local", 
                                                                "Only central", 
                                                                "Only local", 
                                                                "Unclear", 
                                                                "No ORR")),
            Inconsistency= factor(Inconsistency, levels = c("Consistent", 
                                                            "Unclear both in prespecification and in paper", 
                                                            "No prespecification, or no mention", 
                                                            "Unclear in advance but clear in paper", 
                                                            "Central or local in advance but both in paper", 
                                                            "Central or local in advance but unclear in paper",
                                                            "Suspicious of selective reporting")),
            Blindness= factor(Blindness, levels = c("Blinded + non-blinded", 
                                                    "Probably, blinded + non-blinded",
                                                    "Only blinded", 
                                                    "Probably, only blinded", 
                                                    "Only non-blinded", 
                                                    "Probably, only non-blinded",
                                                    "No ORR")),
            Blindness2=factor(Blindness2, levels = c("Reported", "Not reported")))

library(summarytools)
freq(data_ORR)
ctable(x=data_ORR$Blindness2,
       y=data_ORR$Published_paper,
       prop = "c")
