library(tidyverse)
data <- read.csv("data/main_data.csv")
data_PFS <- data %>% 
  select(ID, Inclusion_Exlusion, PFS_Registry, PFS_Protocol, PFS_Prespecified, PFS_Paper, 
         PFS_Inconsistency, PFS_Reason, PFS_Blndeness, Primary_outcome, PFS_primary_outcome, IF) %>% 
  filter(Inclusion_Exlusion=="Inclusion") %>% 
  rename(Registry=PFS_Registry, Protocol=PFS_Protocol, Prespecified=PFS_Prespecified, 
         Published_paper=PFS_Paper, Inconsistency=PFS_Inconsistency, 
         Reason=PFS_Reason, Blindness=PFS_Blndeness) %>% 
  mutate(Registry=case_when(Registry=="Investigator + central"~"Central + local",
                            Registry=="Only central"~"Only central",
                            Registry=="Only investigator"~"Only local",
                            Registry=="Unclear"~"Unclear",
                            Registry=="No PFS"~"No PFS",
                            Registry=="No registry"~"Not available"),
         Protocol=case_when(Protocol=="Investigator + central"~"Central + local",
                            Protocol=="Only central"~"Only central",
                            Protocol=="Only investigator"~"Only local",
                            Protocol=="Unclear"~"Unclear",
                            Protocol=="No PFS"~"No PFS",
                            Protocol=="No protocol"~"Not available"),
         Prespecified=case_when(Prespecified=="Investigator + central"~"Central + local",
                                Prespecified=="Only central"~"Only central",
                                Prespecified=="Only investigator"~"Only local",
                                Prespecified=="Unclear"~"Unclear",
                                Prespecified=="No PFS"~"No PFS",
                                Prespecified=="Not available"~"Not available"),
         Published_paper=case_when(Published_paper=="Investigator + central"~"Central + local",
                                   Published_paper=="Only central"~"Only central",
                                   Published_paper=="Only investigator"~"Only local",
                                   Published_paper=="Unclear"~"Unclear",
                                   Published_paper=="No PFS"~"No PFS"),
         Blindness2=case_when(Blindness=="Non-blinded + blinded"~"Reported",
                              Blindness=="Only blinded"~"Reported",
                              Blindness=="Only non-blinded"~"Reported",
                              Blindness=="Probably, non-blinded + blinded"~"Not reported",
                              Blindness=="Probably, only blinded"~"Not reported",
                              Blindness=="Probably, only non-blinded"~"Not reported",
                              Blindness=="No PFS"~"No PFS"),
         Blindness=case_when(Blindness=="Non-blinded + blinded"~"Blinded + non-blinded",
                             Blindness=="Only blinded"~"Only blinded",
                             Blindness=="Only non-blinded"~"Only non-blinded",
                             Blindness=="Probably, non-blinded + blinded"~"Probably, blinded + non-blinded",
                             Blindness=="Probably, only blinded"~"Probably, only blinded",
                             Blindness=="Probably, only non-blinded"~"Probably, only non-blinded",
                             Blindness=="No PFS"~"No PFS"),
         Inconsistency=case_when(Inconsistency=="Consistent"~"Consistent",
                                 Inconsistency=="Consistent: unclear"~"Unclear",
                                 Inconsistency=="Not prespecified"~"Unclear",
                                 Inconsistency=="Unclear in advance but clear in paper"~"Unclear in advance but clear in paper",
                                 Inconsistency=="Central or local in advance but both in paper"~"Central or local in advance but both in paper",
                                 Inconsistency=="Central or local in advance but unclear in paper"~"Central or local in advance but unclear in paper",
                                 Inconsistency=="Suspicious of selective reporting"~"Not reporting the prespecified outcome"),
         IF_category=case_when(IF>=10~"High_IF",
                               IF<10~"Low_IF")) %>% 
  transform(Registry= factor(Registry, levels = c("Central + local", 
                                                  "Only central", 
                                                  "Only local", 
                                                  "Unclear", 
                                                  "No PFS", 
                                                  "Not available")),
            Protocol= factor(Protocol, levels = c("Central + local", 
                                                  "Only central", 
                                                  "Only local", 
                                                  "Unclear", 
                                                  "No PFS", 
                                                  "Not available")),
            Prespecified= factor(Prespecified, levels = c("Central + local", 
                                                          "Only central", 
                                                          "Only local", 
                                                          "Unclear", 
                                                          "No PFS", 
                                                          "Not available")),
            Published_paper= factor(Published_paper, levels = c("Central + local", 
                                                                "Only central", 
                                                                "Only local", 
                                                                "Unclear", 
                                                                "No PFS")),
            Inconsistency= factor(Inconsistency, levels = c("Consistent",                                               "Unclear in advance but clear in paper", 
                                                            "Central or local in advance but both in paper", 
                                                            "Central or local in advance but unclear in paper",
                                                            "Not reporting the prespecified outcome",
                                                            "Unclear")),
            Blindness= factor(Blindness, levels = c("Blinded + non-blinded", 
                                                    "Probably, blinded + non-blinded",
                                                    "Only blinded", 
                                                    "Probably, only blinded", 
                                                    "Only non-blinded", 
                                                    "Probably, only non-blinded",
                                                    "No PFS")),
            Blindness2=factor(Blindness2, levels = c("Reported", "Not reported")))

library(summarytools)
freq(data_PFS)
ctable(x=data_PFS$Blindness2,
       y=data_PFS$Published_paper,
       prop = "c")


